### ISSUE TITLE
Бэкапы

### ISSUE THREAD

**Issue by dmivilensky** [dmivilensky/highlight#4]
Надо сделать python скрипт, который автоматически запихнет все файлы из files в zip-архив, выгрузит всю базу в json файлы и отправит в одном целом архиве куда-нибудь в хранилище. И, если надо, сделает эти действия с архивом в обратном порядке, добавив к имеющимся записям и файлам сохранённые, если их там нет.

**Comment by skabrits** [comment]
Готово
